USE fetindb;

CREATE TABLE beacons (
    id INT AUTO_INCREMENT PRIMARY KEY,
    beacon VARCHAR(100) NOT NULL,
    tipo VARCHAR(100) NOT NULL,
	status VARCHAR(100) UNIQUE NOT NULL,
    x FLOAT NOT NULL,
    y FLOAT NOT NULL
);
